# Generated by Django 2.2.6 on 2019-11-08 20:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_portugues', models.CharField(max_length=150)),
                ('titulo_english', models.CharField(max_length=150)),
                ('descricao_portugues', models.TextField(blank=True)),
                ('descricao_english', models.TextField(blank=True)),
                ('identifier', models.CharField(max_length=150)),
                ('link_pdf', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revistas.Artigos')),
            ],
        ),
        migrations.CreateModel(
            name='Palavras_chave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=20)),
                ('nome_revista_portugues', models.CharField(max_length=100)),
                ('nome_revista_english', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigos_favoritos', models.ManyToManyField(to='Revistas.Favoritos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('subtitulo', models.CharField(default='Not found', max_length=350)),
                ('corpo', models.TextField()),
                ('data_postagem', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('autor', models.PositiveIntegerField()),
                ('imagem', models.ImageField(blank=True, upload_to='media')),
                ('link_artigo', models.TextField(blank=True)),
                ('revista_relacionada', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Revistas.Revista')),
            ],
        ),
        migrations.CreateModel(
            name='Edicoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicao_portugues', models.CharField(max_length=100)),
                ('edicao_english', models.CharField(max_length=100)),
                ('data_lancamento', models.DateField()),
                ('identifier', models.CharField(max_length=150)),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revistas.Revista')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpo', models.TextField()),
                ('autor', models.PositiveIntegerField()),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revistas.Noticias')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=100)),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revistas.Revista')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('id_usuario', models.PositiveIntegerField()),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revistas.Artigos')),
            ],
        ),
        migrations.AddField(
            model_name='artigos',
            name='autores',
            field=models.ManyToManyField(to='Revistas.Autores'),
        ),
        migrations.AddField(
            model_name='artigos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revistas.Categoria'),
        ),
        migrations.AddField(
            model_name='artigos',
            name='edicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revistas.Edicoes'),
        ),
        migrations.AddField(
            model_name='artigos',
            name='palavras_chave',
            field=models.ManyToManyField(to='Revistas.Palavras_chave'),
        ),
    ]
