# Generated by Django 2.2.6 on 2021-01-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=20)),
                ('nome_revista_portugues', models.CharField(max_length=100)),
                ('nome_revista_english', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, upload_to='media')),
                ('email', models.CharField(blank=True, max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=25)),
                ('local', models.TextField(blank=True)),
                ('sobre', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicao_portugues', models.CharField(max_length=100)),
                ('edicao_english', models.CharField(max_length=100)),
                ('data_lancamento', models.DateField()),
                ('identifier', models.CharField(max_length=150)),
                ('imagem', models.ImageField(blank=True, upload_to='media')),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revistas.Revista')),
            ],
            options={
                'verbose_name': 'Ediçõe',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=100)),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revistas.Revista')),
            ],
        ),
    ]
