# Generated by Django 2.2.6 on 2019-11-16 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Revistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='data_postagem',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='revista',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='revista',
            name='local',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='revista',
            name='sobre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='revista',
            name='telefone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='artigos_favoritos',
            field=models.ManyToManyField(to='Revistas.Artigos'),
        ),
        migrations.DeleteModel(
            name='Favoritos',
        ),
    ]
