# Generated by Django 3.2.8 on 2021-11-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='oai_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
