# Generated by Django 2.2.6 on 2019-12-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revistas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='autor',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='id_autor',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='nome_autor',
            field=models.CharField(default='Not Found', max_length=100),
        ),
    ]
