# Generated by Django 2.2.6 on 2019-11-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revistas', '0002_auto_20191116_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='administrador',
            field=models.BooleanField(default=False),
        ),
    ]
