# Generated by Django 2.2.6 on 2019-11-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revistas', '0003_usuario_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='gerencia_revista',
            field=models.ManyToManyField(to='Revistas.Revista'),
        ),
    ]
