# Generated by Django 2.2.6 on 2021-01-28 16:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visivel', models.BooleanField(default=True, verbose_name='Visível')),
                ('corpo', models.TextField(verbose_name='Corpo do comentário')),
                ('data_postagem', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data de postagem')),
            ],
            options={
                'verbose_name': 'Comentário',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visivel', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=150)),
                ('subtitulo', models.CharField(default='Not found', max_length=350)),
                ('corpo', models.TextField()),
                ('data_postagem', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('imagem', models.ImageField(blank=True, upload_to='media')),
                ('link_artigo', models.TextField(blank=True)),
                ('revista_relacionada', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='revistas.Revista')),
            ],
            options={
                'verbose_name': 'Notícia',
            },
        ),
    ]
