# Generated by Django 2.2.6 on 2021-01-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='artigos_favoritos',
            field=models.ManyToManyField(blank=True, to='artigos.Artigo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='gerencia_revista',
            field=models.ManyToManyField(blank=True, to='revistas.Revista'),
        ),
    ]
