# Generated by Django 3.2.8 on 2021-11-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20211031_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='date_of_birth',
        ),
    ]
