# Generated by Django 2.2.6 on 2021-01-28 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_portugues', models.CharField(max_length=150)),
                ('titulo_english', models.CharField(max_length=150)),
                ('descricao_portugues', models.TextField(blank=True)),
                ('descricao_english', models.TextField(blank=True)),
                ('identifier', models.CharField(max_length=150)),
                ('link_pdf', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Autore',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Avaliaçõe',
            },
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Palavras chave',
            },
        ),
    ]
