# Generated by Django 2.2.6 on 2021-01-28 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artigos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artigo',
            name='autores',
            field=models.ManyToManyField(to='artigos.Autor'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revistas.Categoria'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='edicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revistas.Edicao'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='palavras_chave',
            field=models.ManyToManyField(to='artigos.PalavraChave'),
        ),
    ]
